name: gnn
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.17
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.9.23
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - geopandas==1.0.1
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.1
      - markupsafe==3.0.2
      - multidict==6.6.3
      - numpy==1.24.4
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.3.0
      - propcache==0.3.2
      - psutil==7.0.0
      - pyogrio==0.11.1
      - pyparsing==3.2.3
      - pyproj==3.6.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.4
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - shapely==2.0.7
      - six==1.17.0
      - threadpoolctl==3.6.0
      - torch==1.12.0+cu113
      - torch-cluster==1.6.3
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2
      - torchaudio==0.12.0+cu113
      - torchvision==0.13.0+cu113
      - tqdm==4.67.1
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - yarl==1.20.1
prefix: /work2/08968/eliasm1/frontera/HABITAT_env/miniconda3/envs/gnn
